server:
  port: 8081
  servlet:
    context-path: /albuns-freemium
  error:
    include-message: always
    include-exception: false
    include-stacktrace: on_param
    include-binding-errors: always

spring:
  output:
    ansi:
      enabled: ALWAYS
  ##
  # Spring Security OAuth2 Client
  ##
  security:
    oauth2:
      client:
        provider:
          minhas-figurinhas:
            token-uri: http://localhost:18080/auth/realms/minhas-figurinhas/protocol/openid-connect/token
        registration:
          minhas-figurinhas:
            authorization-grant-type: client_credentials
            client-id: albuns-freemium-client
            client-secret: hHBfTjs6JFZty60eY42Nna3p6x4xVG6X
            scope: albuns:read,albuns:write

##
# Open Feign
##
integrations.resource-server.url: http://localhost:8080/oauth2-resourceserver-minhas-figurinhas/

feign:
  client:
    config:
      minhasFigurinhasClient:
        decode404: true
        loggerLevel: full

logging.level.br.com.zup.edu.freemium.client.MinhasFigurinhasClient: DEBUG